providers:
  file: {}

http:
  routers:
      api:
        rule: "Host(`traefik.lab.test`)"
        service: api@internal
        middlewares:
          - traefik-auth
      main-router:
        rule: "Host(`lab.test`)"
        service: service-id
        tls:
          options: myTLSOptions
  middlewares:
    http-to-https-always:
      redirectScheme:
        scheme: https
    traefik-auth:
      basicAuth:
        users:
          - "traefik:$2y$05$.OGZj9VROg8iYJtv.QcQCuJOxNWM1nk18BI45XIkofEdZNQ8IOsjK"
tls:
  certificates:
    - certFile: /lab.test.crt
      keyFile: /lab.test.key
  options:
    myTLSOptions:
      minVersion: VersionTLS13
      cipherSuites:
        - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
        - TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305
        - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305
        - TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
        - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
