providers:
  file: {}

http:
  middlewares:
    headers:
      headers:
        stsSeconds: 31536000
    http-redirect-https:
      redirectScheme:
        scheme: https
        permanent: true
    traefik-auth:
      basicAuth:
        users:
          # traefik/traefik
          - "traefik:$2y$05$.OGZj9VROg8iYJtv.QcQCuJOxNWM1nk18BI45XIkofEdZNQ8IOsjK"
    lan-whitelist:
      ipWhiteList:
        sourceRange:
          - "192.168.1.0/24"
          - "127.0.0.1/32"
tls:
  stores:
    default:
      defaultCertificate:
        certFile: /etc/traefik/lab.test.crt
        keyFile: /etc/traefik/lab.test.key
  certificates:
    - certFile: /etc/traefik/lab.test.crt
      keyFile: /etc/traefik/lab.test.key
      stores:
        - default
  options:
    myTLSOptions:
      minVersion: VersionTLS12
      cipherSuites:
        - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
        - TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305
        - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305
        - TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
        - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
