---
version: '3'
services:
  www:
    container_name: www
    image: nginx:latest
    restart: "no"
    labels:
      - "traefik.docker.network=traefik"
      - "traefik.http.routers.www.entrypoints=http"
      - "traefik.http.routers.www.rule=Host(`www.lab.test`)"
      - "traefik.http.routers.www.middlewares=http-redirect-https@file,headers@file"
      - "traefik.http.routers.www-secure.entrypoints=https"
      - "traefik.http.routers.www-secure.rule=Host(`www.lab.test`)"
      - "traefik.http.routers.www-secure.middlewares=headers@file"
      - "traefik.http.routers.www-secure.tls=true"
    networks:
      - traefik
    volumes:
      - "./config/default.conf:/etc/nginx/conf.d/default.conf"
      - "./html:/var/www/html:ro"
networks:
  traefik:
    external: true
