---
version: '3'
services:
  jenkins:
    container_name: "jenkins"
    image: jenkinsci/blueocean:latest
    restart: "no"
    privileged: true
    user: root
    labels:
      - "traefik.docker.network=traefik"
      - "traefik.http.routers.jenkins.entrypoints=http"
      - "traefik.http.routers.jenkins.rule=Host(`jenkins.lab.test`)"
      - "traefik.http.routers.jenkins.middlewares=http-redirect-https@file,headers@file"
      - "traefik.http.routers.jenkins-secure.entrypoints=https"
      - "traefik.http.routers.jenkins-secure.rule=Host(`jenkins.lab.test`)"
      - "traefik.http.routers.jenkins-secure.middlewares=headers@file"
      - "traefik.http.routers.jenkins-secure.tls=true"
    ports:
      - "8026:50000"
    networks:
      - backend
      - traefik
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./jenkins_home:/var/jenkins_home
networks:
  traefik:
    external: true
  backend:
    driver: bridge
