version: '3'
services:
  jenkins:
    container_name: "jenkins"
    build: .
    # image: jenkinsci/blueocean:latest
    restart: always
    privileged: true
    user: root
    labels:
      - "traefik.frontend.rule=Host:jenkins.lab.test"
      - "traefik.docker.network=traefik"
    ports:
      - "8025:8080"
      - "8026:50000"
    networks:
      - backend
      - traefik
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./jenkins_home:/var/jenkins_home
networks:
  traefik:
    external:
      name: traefik
  backend:
    driver: bridge
