---
version: '3'
services:
  portainer_nginx:
    build: nginx/
    container_name: "portainer_nginx"
    restart: "no"
    depends_on:
      - portainer_app
    labels: 
      - "traefik.docker.network=traefik"
      - "traefik.http.routers.portainer.entrypoints=http"
      - "traefik.http.routers.portainer.rule=Host(`portainer.lab.test`)"
      - "traefik.http.routers.portainer.middlewares=http-redirect-https@file,headers@file"
      - "traefik.http.routers.portainer-secure.entrypoints=https"
      - "traefik.http.routers.portainer-secure.rule=Host(`portainer.lab.test`)"
      - "traefik.http.routers.portainer-secure.middlewares=headers@file"
      - "traefik.http.routers.portainer-secure.tls=true"
    networks:
      - backend
      - traefik
  portainer_app:
    image: portainer/portainer-ce:latest
    container_name: "portainer_app"
    restart: "no"
#Automatically choose 'Manage the Docker instance where Portainer is running' by adding <--host=unix:///var/run/docker.sock> to the command
    #command: --templates http://portainer_templates/templates.json
    labels: 
      - "traefik.enable=false"
    networks:
      - backend
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/data
networks:
  traefik:
    external: true
  backend:
    driver: bridge
